### ISSUE TITLE
Rotation in PatchHandler3D does not have the intended effect

### ISSUE THREAD

**Issue by filipchristiansen** [EdwardFerdian/4DFlowNet#1]
https://github.com/EdwardFerdian/4DFlowNet/blob/e273730f33f1ed1fd30d922f714e622e5dc70ded/src/Network/PatchHandler3D.py#L217-L224

This does not seem to have the intended effect. `w *= -1` has no effect as it is followed by `w = temp`.

**Comment by EdwardFerdian** [comment]
You are right, thanks for letting me know! 

This is error prone, should've done it with rotation matrix.
Will update the code later, Simply fix the w*= -1 to v *= -1 for now.

**Comment by EdwardFerdian** [comment]
Fixed on master
